import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { gql } from "@apollo/client"
import client from '../apollo-client'

export async function getServerSideProps() {
  const {data} = await client.query({ 
    query: gql`
    query ExampleQuery {
      countries {
        code
        name
        emoji
      }
    }    
    `
  })

  return {
    props: {
      countries: data.countries.slice(0, 6)
    }
  }
}

export default function Home({countries}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          {countries.map((country) => (
            <div key={country.code} className={styles.card}>
              <h3>{country.name}</h3>
              <p>
                {country.code} - {country.emoji}
              </p>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
